name: Build and Deploy Dotnet

on:
  push:
    paths:
      - "./**"
  workflow_dispatch:

env:
# ACR data
  ACR_ADDR: testregistry91.azurecr.io
  ACR_NAME: testregistry91
  ACR_ADMIN_USER: testregistry91
  DOCKER_CMD: "sudo docker"
  IMAGE: python
  # needed to access AKS
  CLUSTER_NAME: k8-cluster2
  CLUSTER_RG: k8-cluster_group2
  NAMESPACE: default
  # keyvault parameters
  KEYVAULTNAME: testKVtomcat2

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      # standard GitHub Action
      - name: Checkout
        uses: actions/checkout@master
      #  with:
      #    ref: master

       # Install pack CLI
      - name: Install buildpack
        run: |
          (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.32.1/pack-v0.32.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)
      # build image
      - name: Run buildpack python
        run: |
          cd dotnet-core/aspnet/
          pack build dotnet-aspnet-sample --buildpack paketo-buildpacks/dotnet-core
